name: Daily Hot News Poster

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 0:00运行（北京时间8:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run poster
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        XIAOHONGSHU_COOKIE: ${{ secrets.XIAOHONGSHU_COOKIE }}
      run: |
        python main.py